export type Page =
  | 'landing'
  | 'login'
  | 'signup'
  | 'courses'
  | 'tutor'
  | 'contact'
  | 'studentDashboard'
  | 'tutorDashboard'
  | 'coursedetails'
  | 'courseManagement'
  | 'tutorProfile'
  | 'tutorSearch'
  | 'virtualClassroom'
  | 'emotionAnalytics';
